# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64ca9825fa55641fa9829420ca6d8895"
name = " urtopia-checkout-extend"
handle = "urtopia-checkout-extend"
application_url = "https://example.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ff1696e5.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
