# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64768d21a7157debe4ac4e00b9737a35"
name = "urtopia-checkout"
handle = "urtopia-checkout-2"
application_url = "https://driver-para-higher-webshots.trycloudflare.com/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://driver-para-higher-webshots.trycloudflare.com/auth/callback",
  "https://driver-para-higher-webshots.trycloudflare.com/auth/shopify/callback",
  "https://driver-para-higher-webshots.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = true
