# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64768d21a7157debe4ac4e00b9737a35"
name = "urtopia-checkout"
handle = "urtopia-checkout-ui"
application_url = "https://boundaries-permanent-ncaa-remix.trycloudflare.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "urtopiacheckout.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://boundaries-permanent-ncaa-remix.trycloudflare.com/auth/callback",
  "https://boundaries-permanent-ncaa-remix.trycloudflare.com/auth/shopify/callback",
  "https://boundaries-permanent-ncaa-remix.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"
